-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Ling.

{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-name-shadowing #-}
module Ling.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Ling.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Ling.Abs.Name where
  prt _ (Ling.Abs.Name i) = doc $ showString i
instance Print Ling.Abs.OpName where
  prt _ (Ling.Abs.OpName i) = doc $ showString i
instance Print Ling.Abs.Program where
  prt i = \case
    Ling.Abs.Prg decs -> prPrec i 0 (concatD [prt 0 decs])

instance Print Ling.Abs.Dec where
  prt i = \case
    Ling.Abs.DDef name optsig term -> prPrec i 0 (concatD [prt 0 name, prt 0 optsig, doc (showString "="), prt 0 term])
    Ling.Abs.DSig name term -> prPrec i 0 (concatD [prt 0 name, doc (showString ":"), prt 0 term])
    Ling.Abs.DDat name connames -> prPrec i 0 (concatD [doc (showString "data"), prt 0 name, doc (showString "="), prt 0 connames])
    Ling.Abs.DAsr assertion -> prPrec i 0 (concatD [doc (showString "assert"), prt 0 assertion])

instance Print Ling.Abs.Assertion where
  prt i = \case
    Ling.Abs.AEq term1 term2 optsig -> prPrec i 0 (concatD [prt 0 term1, doc (showString "="), prt 0 term2, prt 0 optsig])

instance Print Ling.Abs.ConName where
  prt i = \case
    Ling.Abs.CN name -> prPrec i 0 (concatD [doc (showString "`"), prt 0 name])

instance Print [Ling.Abs.ConName] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "|"), prt 0 xs]

instance Print Ling.Abs.OptSig where
  prt i = \case
    Ling.Abs.NoSig -> prPrec i 0 (concatD [])
    Ling.Abs.SoSig term -> prPrec i 0 (concatD [doc (showString ":"), prt 0 term])

instance Print [Ling.Abs.Dec] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Ling.Abs.VarDec where
  prt i = \case
    Ling.Abs.VD name optsig -> prPrec i 0 (concatD [doc (showString "("), prt 0 name, prt 0 optsig, doc (showString ")")])

instance Print Ling.Abs.ChanDec where
  prt i = \case
    Ling.Abs.CD name optrepl optsession -> prPrec i 0 (concatD [prt 0 name, prt 0 optrepl, prt 0 optsession])

instance Print [Ling.Abs.ChanDec] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Ling.Abs.Branch where
  prt i = \case
    Ling.Abs.Br conname term -> prPrec i 0 (concatD [prt 0 conname, doc (showString "->"), prt 0 term])

instance Print [Ling.Abs.Branch] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Ling.Abs.Literal where
  prt i = \case
    Ling.Abs.LInteger n -> prPrec i 0 (concatD [prt 0 n])
    Ling.Abs.LDouble d -> prPrec i 0 (concatD [prt 0 d])
    Ling.Abs.LString str -> prPrec i 0 (concatD [printString str])
    Ling.Abs.LChar c -> prPrec i 0 (concatD [prt 0 c])

instance Print Ling.Abs.ATerm where
  prt i = \case
    Ling.Abs.Var name -> prPrec i 0 (concatD [prt 0 name])
    Ling.Abs.Op opname -> prPrec i 0 (concatD [prt 0 opname])
    Ling.Abs.Lit literal -> prPrec i 0 (concatD [prt 0 literal])
    Ling.Abs.Con conname -> prPrec i 0 (concatD [prt 0 conname])
    Ling.Abs.TTyp -> prPrec i 0 (concatD [doc (showString "Type")])
    Ling.Abs.TProto rsessions -> prPrec i 0 (concatD [doc (showString "<"), prt 0 rsessions, doc (showString ">")])
    Ling.Abs.Paren term optsig -> prPrec i 0 (concatD [doc (showString "("), prt 0 term, prt 0 optsig, doc (showString ")")])
    Ling.Abs.End -> prPrec i 0 (concatD [doc (showString "end")])
    Ling.Abs.Par rsessions -> prPrec i 0 (concatD [doc (showString "{"), prt 0 rsessions, doc (showString "}")])
    Ling.Abs.Ten rsessions -> prPrec i 0 (concatD [doc (showString "["), prt 0 rsessions, doc (showString "]")])
    Ling.Abs.Seq rsessions -> prPrec i 0 (concatD [doc (showString "[:"), prt 0 rsessions, doc (showString ":]")])

instance Print [Ling.Abs.ATerm] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Ling.Abs.Term where
  prt i = \case
    Ling.Abs.RawApp aterm aterms -> prPrec i 3 (concatD [prt 0 aterm, prt 0 aterms])
    Ling.Abs.Case term branchs -> prPrec i 2 (concatD [doc (showString "case"), prt 0 term, doc (showString "of"), doc (showString "{"), prt 0 branchs, doc (showString "}")])
    Ling.Abs.Snd term csession -> prPrec i 2 (concatD [doc (showString "!"), prt 3 term, prt 0 csession])
    Ling.Abs.Rcv term csession -> prPrec i 2 (concatD [doc (showString "?"), prt 3 term, prt 0 csession])
    Ling.Abs.Dual term -> prPrec i 2 (concatD [doc (showString "~"), prt 2 term])
    Ling.Abs.TRecv name -> prPrec i 2 (concatD [doc (showString "<-"), prt 0 name])
    Ling.Abs.Loli term1 term2 -> prPrec i 1 (concatD [prt 2 term1, doc (showString "-o"), prt 1 term2])
    Ling.Abs.TFun term1 term2 -> prPrec i 1 (concatD [prt 2 term1, doc (showString "->"), prt 1 term2])
    Ling.Abs.TSig term1 term2 -> prPrec i 1 (concatD [prt 2 term1, doc (showString "**"), prt 1 term2])
    Ling.Abs.Let name optsig term1 term2 -> prPrec i 1 (concatD [doc (showString "let"), prt 0 name, prt 0 optsig, doc (showString "="), prt 0 term1, doc (showString "in"), prt 0 term2])
    Ling.Abs.Lam term1 term2 -> prPrec i 0 (concatD [doc (showString "\\"), prt 2 term1, doc (showString "->"), prt 0 term2])
    Ling.Abs.TProc chandecs proc_ -> prPrec i 0 (concatD [doc (showString "proc"), doc (showString "("), prt 0 chandecs, doc (showString ")"), prt 0 proc_])

instance Print Ling.Abs.Proc where
  prt i = \case
    Ling.Abs.PAct act -> prPrec i 1 (concatD [prt 0 act])
    Ling.Abs.PPrll procs -> prPrec i 1 (concatD [doc (showString "("), prt 0 procs, doc (showString ")")])
    Ling.Abs.PRepl replkind aterm withindex proc_ -> prPrec i 1 (concatD [prt 0 replkind, doc (showString "^"), prt 0 aterm, prt 0 withindex, prt 1 proc_])
    Ling.Abs.PNxt proc_1 proc_2 -> prPrec i 0 (concatD [prt 1 proc_1, prt 0 proc_2])
    Ling.Abs.PDot proc_1 proc_2 -> prPrec i 0 (concatD [prt 1 proc_1, doc (showString "."), prt 0 proc_2])
    Ling.Abs.PSem proc_1 proc_2 -> prPrec i 0 (concatD [prt 1 proc_1, doc (showString ";"), prt 0 proc_2])

instance Print [Ling.Abs.Proc] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "|"), prt 0 xs]

instance Print Ling.Abs.ReplKind where
  prt i = \case
    Ling.Abs.ReplSeq -> prPrec i 0 (concatD [doc (showString "sequence")])
    Ling.Abs.ReplPar -> prPrec i 0 (concatD [doc (showString "parallel")])

instance Print Ling.Abs.WithIndex where
  prt i = \case
    Ling.Abs.NoIndex -> prPrec i 0 (concatD [])
    Ling.Abs.SoIndex name -> prPrec i 0 (concatD [doc (showString "with"), prt 0 name])

instance Print Ling.Abs.Act where
  prt i = \case
    Ling.Abs.Nu newalloc -> prPrec i 0 (concatD [prt 0 newalloc])
    Ling.Abs.Split split -> prPrec i 0 (concatD [prt 0 split])
    Ling.Abs.Send name aterm -> prPrec i 0 (concatD [doc (showString "send"), prt 0 name, prt 0 aterm])
    Ling.Abs.NewSend name optsession aterm -> prPrec i 0 (concatD [prt 0 name, prt 0 optsession, doc (showString "<-"), prt 0 aterm])
    Ling.Abs.Recv name vardec -> prPrec i 0 (concatD [doc (showString "recv"), prt 0 name, prt 0 vardec])
    Ling.Abs.NewRecv name1 optsig name2 -> prPrec i 0 (concatD [doc (showString "let"), prt 0 name1, prt 0 optsig, doc (showString "<-"), prt 0 name2])
    Ling.Abs.LetRecv name optsig aterm -> prPrec i 0 (concatD [doc (showString "let"), prt 0 name, prt 0 optsig, doc (showString "<="), prt 0 aterm])
    Ling.Abs.Ax asession chandecs -> prPrec i 0 (concatD [doc (showString "fwd"), prt 0 asession, doc (showString "("), prt 0 chandecs, doc (showString ")")])
    Ling.Abs.SplitAx n asession name -> prPrec i 0 (concatD [doc (showString "fwd"), prt 0 n, prt 0 asession, prt 0 name])
    Ling.Abs.At aterm topcpatt -> prPrec i 0 (concatD [doc (showString "@"), prt 0 aterm, prt 0 topcpatt])
    Ling.Abs.LetA name optsig aterm -> prPrec i 0 (concatD [doc (showString "let"), prt 0 name, prt 0 optsig, doc (showString "="), prt 0 aterm])

instance Print Ling.Abs.ASession where
  prt i = \case
    Ling.Abs.AS aterm -> prPrec i 0 (concatD [prt 0 aterm])

instance Print Ling.Abs.Split where
  prt i = \case
    Ling.Abs.PatSplit name optas cpatt -> prPrec i 0 (concatD [doc (showString "split"), prt 0 name, prt 0 optas, prt 0 cpatt])
    Ling.Abs.ParSplit name chandecs -> prPrec i 0 (concatD [prt 0 name, doc (showString "{"), prt 0 chandecs, doc (showString "}")])
    Ling.Abs.TenSplit name chandecs -> prPrec i 0 (concatD [prt 0 name, doc (showString "["), prt 0 chandecs, doc (showString "]")])
    Ling.Abs.SeqSplit name chandecs -> prPrec i 0 (concatD [prt 0 name, doc (showString "[:"), prt 0 chandecs, doc (showString ":]")])

instance Print Ling.Abs.OptAs where
  prt i = \case
    Ling.Abs.NoAs -> prPrec i 0 (concatD [])
    Ling.Abs.SoAs -> prPrec i 0 (concatD [doc (showString "as")])

instance Print Ling.Abs.TopCPatt where
  prt i = \case
    Ling.Abs.OldTopPatt chandecs -> prPrec i 0 (concatD [doc (showString "("), prt 0 chandecs, doc (showString ")")])
    Ling.Abs.ParTopPatt cpatts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 cpatts, doc (showString "}")])
    Ling.Abs.TenTopPatt cpatts -> prPrec i 0 (concatD [doc (showString "["), prt 0 cpatts, doc (showString "]")])
    Ling.Abs.SeqTopPatt cpatts -> prPrec i 0 (concatD [doc (showString "[:"), prt 0 cpatts, doc (showString ":]")])

instance Print Ling.Abs.CPatt where
  prt i = \case
    Ling.Abs.ChaPatt chandec -> prPrec i 0 (concatD [prt 0 chandec])
    Ling.Abs.ParPatt cpatts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 cpatts, doc (showString "}")])
    Ling.Abs.TenPatt cpatts -> prPrec i 0 (concatD [doc (showString "["), prt 0 cpatts, doc (showString "]")])
    Ling.Abs.SeqPatt cpatts -> prPrec i 0 (concatD [doc (showString "[:"), prt 0 cpatts, doc (showString ":]")])

instance Print [Ling.Abs.CPatt] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Ling.Abs.OptSession where
  prt i = \case
    Ling.Abs.NoSession -> prPrec i 0 (concatD [])
    Ling.Abs.SoSession rsession -> prPrec i 0 (concatD [doc (showString ":"), prt 0 rsession])

instance Print Ling.Abs.RSession where
  prt i = \case
    Ling.Abs.Repl term optrepl -> prPrec i 0 (concatD [prt 0 term, prt 0 optrepl])

instance Print [Ling.Abs.RSession] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Ling.Abs.OptRepl where
  prt i = \case
    Ling.Abs.One -> prPrec i 0 (concatD [])
    Ling.Abs.Some aterm -> prPrec i 0 (concatD [doc (showString "^"), prt 0 aterm])

instance Print Ling.Abs.CSession where
  prt i = \case
    Ling.Abs.Cont term -> prPrec i 0 (concatD [doc (showString "."), prt 1 term])
    Ling.Abs.Done -> prPrec i 0 (concatD [])

instance Print Ling.Abs.AllocTerm where
  prt i = \case
    Ling.Abs.AVar name -> prPrec i 0 (concatD [prt 0 name])
    Ling.Abs.ALit literal -> prPrec i 0 (concatD [prt 0 literal])
    Ling.Abs.AParen term optsig -> prPrec i 0 (concatD [doc (showString "("), prt 0 term, prt 0 optsig, doc (showString ")")])

instance Print [Ling.Abs.AllocTerm] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Ling.Abs.NewSig where
  prt i = \case
    Ling.Abs.NoNewSig -> prPrec i 0 (concatD [])
    Ling.Abs.NewTypeSig term -> prPrec i 0 (concatD [doc (showString ":*"), prt 0 term])
    Ling.Abs.NewSessSig term -> prPrec i 0 (concatD [doc (showString ":"), prt 0 term])

instance Print Ling.Abs.NewPatt where
  prt i = \case
    Ling.Abs.TenNewPatt cpatts -> prPrec i 0 (concatD [doc (showString "["), prt 0 cpatts, doc (showString "]")])
    Ling.Abs.SeqNewPatt cpatts -> prPrec i 0 (concatD [doc (showString "[:"), prt 0 cpatts, doc (showString ":]")])
    Ling.Abs.CntNewPatt name newsig -> prPrec i 0 (concatD [doc (showString "("), prt 0 name, prt 0 newsig, doc (showString ")")])

instance Print Ling.Abs.NewAlloc where
  prt i = \case
    Ling.Abs.New newpatt -> prPrec i 0 (concatD [doc (showString "new"), prt 0 newpatt])
    Ling.Abs.NewSAnn term optsig newpatt -> prPrec i 0 (concatD [doc (showString "new/"), doc (showString "("), prt 0 term, prt 0 optsig, doc (showString ")"), prt 0 newpatt])
    Ling.Abs.NewNAnn opname allocterms newpatt -> prPrec i 0 (concatD [prt 0 opname, prt 0 allocterms, prt 0 newpatt])
