# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, alex, happy, lens }:

cabal.mkDerivation (self: {
  pname = "ll2";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ lens ];
  buildTools = [ alex happy ];
  meta = {
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
