#!/bin/bash

testname=con_dup.t
command=ling
args=( --check con_dup.ll )
exit_code=1
stdin_file=/dev/null
stdout_file=/dev/null
stderr_file=stderr
sources=( con_dup.ll )
products=( )

# Environment variables:
env_vars=( )

setup(){
  : Perform here actions to be run before the tested program
}

munge(){
  : Munge here the results of the tested program to ease the check
}

check(){
  check_exit_code &&
  check_stderr &&
  check_stdout &&
  check_products &&
  : Perform here extra checks on the tested program
}

explain(){
  explain_exit_code
  explain_stdout
  explain_stderr
  explain_products
  : Explain here more potential differences
}

teardown(){
  : Undo here the actions of setup
}
