

module MiniC.Abs where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
newtype TIdent = TIdent String deriving (Eq, Ord, Show, Read)
data Prg = PPrg [Def]
  deriving (Eq, Ord, Show, Read)

data Dec = Dec QTyp Ident [Arr]
  deriving (Eq, Ord, Show, Read)

data Def = DDef Dec [Dec] [Stm] | DSig Dec [Dec] | DDec Dec
  deriving (Eq, Ord, Show, Read)

data Typ
    = TName TIdent
    | TStr [Fld]
    | TUni [Fld]
    | TEnum [Enm]
    | TVoid
    | TPtr Typ
  deriving (Eq, Ord, Show, Read)

data Enm = EEnm Ident | ECst Ident Exp
  deriving (Eq, Ord, Show, Read)

data Fld = FFld Typ Ident [Arr]
  deriving (Eq, Ord, Show, Read)

data Arr = AArr Exp
  deriving (Eq, Ord, Show, Read)

data QTyp = QTyp Qual Typ
  deriving (Eq, Ord, Show, Read)

data Qual = NoQual | QConst
  deriving (Eq, Ord, Show, Read)

data Stm
    = SDec Dec Init
    | SPut LVal Exp
    | SFor Stm Exp Stm [Stm]
    | SSwi Exp [Branch]
  deriving (Eq, Ord, Show, Read)

data Branch = Case Exp [Stm]
  deriving (Eq, Ord, Show, Read)

data Init = NoInit | SoInit Exp
  deriving (Eq, Ord, Show, Read)

data Literal
    = LInteger Integer | LDouble Double | LString String | LChar Char
  deriving (Eq, Ord, Show, Read)

data UOp = UAmp | UPtr | UPlus | UMinus | UTilde | UBang
  deriving (Eq, Ord, Show, Read)

data Exp
    = EVar Ident
    | ELit Literal
    | EParen Exp
    | EArw Exp Ident
    | EFld Exp Ident
    | EArr Exp Exp
    | EApp Exp [Exp]
    | UOp UOp Exp
    | Mul Exp Exp
    | Div Exp Exp
    | Mod Exp Exp
    | Add Exp Exp
    | Sub Exp Exp
    | Lsl Exp Exp
    | Lsr Exp Exp
    | Lt Exp Exp
    | Gt Exp Exp
    | Le Exp Exp
    | Ge Exp Exp
    | Eq Exp Exp
    | NEq Exp Exp
    | And Exp Exp
    | Xor Exp Exp
    | Ior Exp Exp
    | Land Exp Exp
    | Lor Exp Exp
    | Cond Exp Exp Exp
  deriving (Eq, Ord, Show, Read)

data LVal
    = LVar Ident
    | LArw LVal Ident
    | LFld LVal Ident
    | LArr LVal Exp
    | LPtr LVal
  deriving (Eq, Ord, Show, Read)
