{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module MiniC.Print where

-- pretty-printer generated by the BNF converter

import MiniC.Abs
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))


instance Print Op where
  prt _ (Op i) = doc (showString ( i))



instance Print Prg where
  prt i e = case e of
   PPrg defs -> prPrec i 0 (concatD [prt 0 defs])


instance Print Dec where
  prt i e = case e of
   Dec qtyp id arrs -> prPrec i 0 (concatD [prt 0 qtyp , prt 0 id , prt 0 arrs])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Def where
  prt i e = case e of
   DDef dec decs stms -> prPrec i 0 (concatD [prt 0 dec , doc (showString "(") , prt 0 decs , doc (showString ")") , doc (showString "{") , prt 0 stms , doc (showString "}")])
   DSig dec decs -> prPrec i 0 (concatD [prt 0 dec , doc (showString "(") , prt 0 decs , doc (showString ")") , doc (showString ";")])
   DDec dec -> prPrec i 0 (concatD [prt 0 dec , doc (showString ";")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Typ where
  prt i e = case e of
   TInt  -> prPrec i 0 (concatD [doc (showString "int")])
   TDouble  -> prPrec i 0 (concatD [doc (showString "double")])
   TStr flds -> prPrec i 0 (concatD [doc (showString "struct") , doc (showString "{") , prt 0 flds , doc (showString "}")])
   TUni flds -> prPrec i 0 (concatD [doc (showString "union") , doc (showString "{") , prt 0 flds , doc (showString "}")])
   TVoid  -> prPrec i 0 (concatD [doc (showString "void")])
   TPtr typ -> prPrec i 0 (concatD [prt 0 typ , doc (showString "*")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Fld where
  prt i e = case e of
   FFld typ id arrs -> prPrec i 0 (concatD [prt 0 typ , prt 0 id , prt 0 arrs])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Arr where
  prt i e = case e of
   AArr exp -> prPrec i 0 (concatD [doc (showString "[") , prt 0 exp , doc (showString "]")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print QTyp where
  prt i e = case e of
   QTyp qual typ -> prPrec i 0 (concatD [prt 0 qual , prt 0 typ])


instance Print Qual where
  prt i e = case e of
   NoQual  -> prPrec i 0 (concatD [])
   QConst  -> prPrec i 0 (concatD [doc (showString "const")])


instance Print Stm where
  prt i e = case e of
   SDec dec init -> prPrec i 0 (concatD [prt 0 dec , prt 0 init])
   SPut lval exp -> prPrec i 0 (concatD [prt 0 lval , doc (showString "=") , prt 0 exp])
   SFor stm0 exp stm stms -> prPrec i 0 (concatD [doc (showString "for") , doc (showString "(") , prt 0 stm0 , doc (showString ";") , prt 0 exp , doc (showString ";") , prt 0 stm , doc (showString ")") , doc (showString "{") , prt 0 stms , doc (showString "}")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Init where
  prt i e = case e of
   NoInit  -> prPrec i 0 (concatD [])
   SoInit exp -> prPrec i 0 (concatD [doc (showString "=") , prt 0 exp])


instance Print Exp where
  prt i e = case e of
   EVar id -> prPrec i 4 (concatD [prt 0 id])
   ELit n -> prPrec i 4 (concatD [prt 0 n])
   EArw exp id -> prPrec i 3 (concatD [prt 3 exp , doc (showString "->") , prt 0 id])
   EFld exp id -> prPrec i 3 (concatD [prt 3 exp , doc (showString ".") , prt 0 id])
   EArr exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "[") , prt 0 exp , doc (showString "]")])
   EInf exp0 op exp -> prPrec i 2 (concatD [prt 2 exp0 , prt 0 op , prt 3 exp])
   EPtr exp -> prPrec i 0 (concatD [doc (showString "*") , prt 3 exp])
   EApp id exps -> prPrec i 0 (concatD [prt 0 id , doc (showString "(") , prt 0 exps , doc (showString ")")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print LVal where
  prt i e = case e of
   LVar id -> prPrec i 3 (concatD [prt 0 id])
   LArw lval id -> prPrec i 2 (concatD [prt 2 lval , doc (showString "->") , prt 0 id])
   LFld lval id -> prPrec i 2 (concatD [prt 2 lval , doc (showString ".") , prt 0 id])
   LArr lval exp -> prPrec i 2 (concatD [prt 2 lval , doc (showString "[") , prt 0 exp , doc (showString "]")])
   LPtr lval -> prPrec i 0 (concatD [doc (showString "*") , prt 2 lval])



